### ISSUE TITLE
Is there a way I can use dotnet 6 preview by change something in dockerfile.

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode-remote-try-dotnetcore#20]
I am looking for testing dotnet 6. How I can do that by change something in dockerfile and devcontainer.json and dotnet 6 environment is ready for testing.

**Comment by Chuxel** [comment]
Yep! In fact, this is why the source dockerfile is referenced.  Just copy the contents of the [`.devcontainer` folder](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/dotnet/.devcontainer) from that location, update `devcontainer.json` to reference `6.0` for the `VARIANT` and update `dockerfile` to reference `base.Dockerfile`.

**Comment by anirugu** [comment]
@Chuxel  Thanks for help.

I tried to get 6.0 but I didn't found it. Is this repo exist on docker as well, where I can find other tags?. Please check the screenshot 
![Screenshot from 2021-02-26 13-17-17](https://user-images.githubusercontent.com/35772421/109271146-1bcdbd00-7835-11eb-9ebe-baf25116a0c4.png)

**Comment by anirugu** [comment]
I look into https://mcr.microsoft.com/v2/vscode/devcontainers/dotnet/tags/list and didn't find the 6.0 

I change the path to FROM mcr.microsoft.com/dotnet/sdk:${VARIANT}-focal and comentout the remoteuser and it's working for me for now.

**Comment by anirugu** [comment]
@Chuxel Thanks, my problem fixed. Your earlier comment is correct.
