### ISSUE TITLE
Debugging fails after first time

### ISSUE THREAD

**Issue by trondhindenes** [Microsoft/vscode-remote-try-dotnetcore#3]
It looks like starting and stopping the debugger doesn't quite clean up, so when I try to debug a second time I get an error that the port is already in use.
If I start then stop the debugger, the app is still running on port 9000, so there's something that doesn't get stopped in the "debug container" when I stop the task in vscode.

**Comment by Chuxel** [comment]
@trondhindenes I, just ushed an upate that should fix this.  There was a problem with the launch config and the container was using .NET Core 2.2 instead of 2.1 like the project.

See if this resolves the problem for you and let us know if it does not.

**Comment by trondhindenes** [comment]
Thanks, will test!

**Comment by trondhindenes** [comment]
Yup, working after pulling the update in the example repo, thanks! Closing.
