### ISSUE TITLE
libhostpolicy.so: file too short

### ISSUE THREAD

**Issue by kcwms** [microsoft/vscode-remote-try-dotnetcore#4]
The host machine has a duel boot of Manjaro 18.04 and WIN10

Following the instructions [here](https://code.visualstudio.com/docs/remote/containers#_getting-started) , I receive the following error as soon as I try and run `dotnet restore` when using  Manjaro but works as expected on the WIN10 partition.

```
Failed to load H�, error: /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.11/libhostpolicy.so: file too short
An error occurred while loading required library libhostpolicy.so from [/usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.11]
```
```
# pwd
/workspaces/vscode-remote-try-dotnetcore
# ls -hl /usr/share/dotnet/shared/Microsoft.NETCore.App/2.1.11/ | grep lib
-rwxr-xr-x 1 1004 sudo 3.0M Apr 17 21:26 libclrjit.so
-rwxr-xr-x 1 1004 sudo 9.8M Apr 17 21:27 libcoreclr.so
-rwxr-xr-x 1 1004 sudo 688K Apr 17 21:27 libcoreclrtraceptprovider.so
-rwxr-xr-x 1 1004 sudo 1.1M Apr 17 21:27 libdbgshim.so
-rwxr-xr-x 1 1004 sudo    0 Apr 17 23:57 libhostpolicy.so
-rwxr-xr-x 1 1004 sudo    0 Apr 17 21:27 libmscordaccore.so
-rwxr-xr-x 1 1004 sudo    0 Apr 17 21:27 libmscordbi.so
-rwxr-xr-x 1 1004 sudo    0 Apr 17 21:27 libsos.so
-rwxr-xr-x 1 1004 sudo    0 Apr 17 21:27 libsosplugin.so
-rw-r--r-- 1 1004 sudo    0 Apr 17 22:21 mscorlib.dll

```
![vscode-remote-try-dotnetcore-20190519-](https://user-images.githubusercontent.com/29052675/57994328-a1321400-7a8a-11e9-90f5-dba5c29ef34b.png)

**Comment by Chuxel** [comment]
@kcwms There's no official Docker package for Manjaro to my knowledge - This is likely due to some sort of issue with Docker and Manjaro. Where did you install from? AUR? I'm unable to repro on a Ubuntu 18.04 native machine or VMs running CentOS or Debian.

It has been a while since this was first raised, I'd try to update Docker and see if the problem has resolved since.

**Comment by kcwms** [comment]
@Chuxel I've since had to wipe Manjaro, and Linux in general, from my hard drive... clients need some vb work done and I needed the space... so we can just close this.

But I would not have used the UAR. That I recall.

**Comment by Chuxel** [comment]
@kcwms Sounds good - thanks for reporting it!
