### ISSUE TITLE
C# and C++ ?

### ISSUE THREAD

**Issue by rajesh-chawla** [microsoft/vscode-remote-try-dotnetcore#7]
I'm working on a project in C# that invokes c++. Is it a feasible scenario to push the development of both languages into the same docker container?

**Comment by Chuxel** [comment]
@rajesh-chawla Yes, absolutely.  An easy way to show this is to start with the C++ dev container Dockerfile and devcontainer.json [from here](https://github.com/microsoft/vscode-dev-containers/tree/master/containers/cpp/.devcontainer) -- or pick C++ using the Remote-Containers: Add Development Container Configuration Files... and then make some edits.

1. In the Dockerfile, change `FROM debian:9` to `FROM mcr.microsoft.com/dotnet/core/sdk:2.2`
2. Add the C# extension into the extensions list in devcontainer.json:

    ```json
    "extensions": [
        "ms-vscode.cpptools",
        "ms-vscode.csharp"
    ]
   ```
3. Reopen the folder in a container (or rebuild if its already open).

For why this works, switching the `FROM` ensures the right .NET Core dependencies are installed, and then this `"runArgs"` line in devcontainer.json ensures the C++ debugger works:

```json
"runArgs": ["--cap-add=SYS_PTRACE", "--security-opt", "seccomp=unconfined"]
```

**Comment by rajesh-chawla** [comment]
That's pretty cool this is a supported scenario. I started with the C++ project, modified the FROM line to point to sdk:2.2 & added c# to the extensions. 

I can compile the program with no issues, though when I try to debug, I get the error that 'cppdbg' is not supported (in launch.json). I'm guessing I need to change the type to coreclr to launch the c# code. Is there anything else I should look to modify?

**Comment by rajesh-chawla** [comment]
Confirmed running -- works with .net 3.0 and g++. Excellent!!

Next step is to add cmake and get things configured for our environment.

**Comment by rajesh-chawla** [comment]
Unfortunately, I've lost intellisense when I code in the container. How can I go about troubleshooting this?
